## Crash Course in PyTorch

### Part 0 - Introduction

#### Instructor: Tudor Cebere


PyTorch is a Python library used for high performance tensor operations.

PyTorch internals are written in C++ for memory-friendly operations and it exposes a set of primitive routines to a high level API in Python, due to it's ease of use and beginner friendly syntax. PyTorch exposes it's API to C++, rust <3 , Haskell, swift and it can be compiled to other frameworks as well.

It's being used mainly in Python due to it's ease of prototyping and clean syntax, the computational heave operations being forwarded to the C++ core.

## What is a Tensor?

We can look at a Tensor as a multidimensional matrix or a generalization of a vector. Let's try to define  what the tensor behavior should be from a computer scientist. Let's imagine that you have a tensor `v`. What will you get if you try to get the first element of a tensor:
* If `v` is a 4D array, the requested element will be a 3D tensor.
* If `v` is a 3D array, the requested element will be a 2D tensor (or a matrix).
* If `v` is a 2D array, the requested element will be a 1D tensor (or a vector).
* If `v` is a 1D array, the requested element will be a scalar.
* If `v` is a scalar, the request element will raise an error.

In other words, let's imagine the dimensions of a tensor:

![](https://miro.medium.com/max/2088/1*TPauIPgMOuwowxd53zNKVA.png)

In [43]:
# Note: the notebook cells are stateful, you need to run this once per session.
import torch as th
import sys

### Creating a Tensor

In [44]:
# Note: note the fact that the int types are converted to float. Why?

one_dimension_tensor = th.Tensor([1, 2, 3])

In [45]:
# Note: Lists in python have no restriction on their internal types and almost all numerical types in python
# can be converted to float.

another_one_dimensional_int_tensor = th.Tensor([False, True, 5])

In [62]:
# Note: When creating a tensor, you can specify the dtype on which to cast the data. 

a = th.ones((2, 3), dtype=th.int)
print(a)

mask = th.zeros((2, 3, 4), dtype=th.bool)
print(mask)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]],

        [[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]])


In [63]:
# Note: The underlying data type can be specified by running custom Tensors as well, for
# example: LongTensor

v = th.LongTensor([1,2,3])   # A Tensor of type Long
print(f"LongTensor: {v}")

LongTensor: tensor([1, 2, 3])


In [67]:
# Initialize each element with a random number sampled from the uniform distribution.
uniform = th.rand(2, 3)
print(f"From the uniform distribution:\n{uniform}\n")

# Initialize each element with a random number sampled from the normal distribution.
normal = th.randn(2, 3)
print(f"From the normal distribution:\n{normal}\n")

# Initialize each element with a permutation from a range.
perm = th.randperm(4)
print(f"From permutations:\n{perm}\n")

From the uniform distribution:
tensor([[0.6843, 0.3134, 0.4077],
        [0.1593, 0.6391, 0.5984]])

From the normal distribution:
tensor([[ 0.5934, -0.9292, -0.7783],
        [-0.2972, -0.0417,  1.5236]])

From permutations:
tensor([3, 1, 2, 0])



In [ ]:

v = torch.linspace(1, 10, steps=10) # Create a Tensor with 10 linear points for (1, 10) inclusively
v = torch.logspace(start=-10, end=10, steps=5) # Size 5: 1.0e-10 1.0e-05 1.0e+00, 1.0e+05, 1.0e+10

### Tensor indexing

In [52]:
# Tip: If you are familiar with NumPy, the indexing is similar!

x = th.Tensor(2, 3)  # An un-initialized Tensor object. x holds random garbage data.

print(x)

tensor([[ 3.7343e+19,  4.5713e-41,  3.7349e+19],
        [ 4.5713e-41, -4.1430e+19,  4.5713e-41]])


In [53]:
# let's get the first array
print(x[0])

tensor([3.7343e+19, 4.5713e-41, 3.7349e+19])


In [55]:
# let's get the second element from the first array
print(x[0][1])

# similar to:
print(x[0, 1])

tensor(4.5713e-41)
tensor(4.5713e-41)


In [56]:
# .size() gives you good hints about how you can do the indexing!
print(x.size())

torch.Size([2, 3])


In [57]:
# .numel() gives you information about the numer of elements in the tensor (this can become huge)

print(x.numel())

6


In [59]:
# your Swiss knife when it comes to tensor shaping is view:
x = th.randn(2, 3)

# lets ssee our tensor unrolled
y = x.view(6)

# what a -1 on a tensor dimension mean when viewing the tensor?
z = x.view(-1, 2)

print(y)
print(z)

tensor([-0.5220,  0.6634, -0.8574, -0.4369, -0.8585,  0.1533])
tensor([[-0.5220,  0.6634],
        [-0.8574, -0.4369],
        [-0.8585,  0.1533]])


## Tensor manipulation

In [ ]:
v = torch.arange(9)
v = v.view(3, 3)

In [ ]:
# Concatenation
torch.cat((x, x, x), 0)          # Concatenate in the 0 dimension

# Stack
r = torch.stack((v, v))

In [ ]:
# Index select
# 0 2
# 3 5
# 6 8
indices = torch.LongTensor([0, 2])
r = torch.index_select(v, 1, indices) # Select element 0 and 2 for each dimension 1.

# Masked select
# 0  0  0
# 1  1  1
# 1  1  1
mask = v.ge(3)

# Size 6: 3 4 5 6 7 8
r = torch.masked_select(v, mask)

In [ ]:
t = torch.ones(2,1,2,1) # Size 2x1x2x1
r = torch.squeeze(t)     # Size 2x2
r = torch.squeeze(t, 1)  # Squeeze dimension 1: Size 2x2x1

# Un-squeeze a dimension
x = torch.Tensor([1, 2, 3])
r = torch.unsqueeze(x, 0)       # Size: 1x3
r = torch.unsqueeze(x, 1)       # Size: 3x1

In [ ]:
# Transpose dim 0 and 1
r = torch.transpose(v, 0, 1)

## Point-wise operations

In [ ]:
### Math operations
f= torch.FloatTensor([-1, -2, 3])
r = torch.abs(f)      # 1 2 3

# Add x, y and scalar 10 to all elements
r = torch.add(x, 10)
r = torch.add(x, 10, y)

# Clamp the value of a Tensor
r = torch.clamp(v, min=-0.5, max=0.5)

# Element-wise divide
r = torch.div(v, v+0.03)

# Element-wise multiple
r = torch.mul(v, v)

## Comparison equation

In [ ]:
### Comparison
# Size 3x3: Element-wise comparison
r = torch.eq(v, v)

# Max element with corresponding index
r = torch.max(v, 1)

## Matrix multiplication


In [ ]:

mat = torch.randn(2, 4)
vec = torch.randn(4)
r = torch.mv(mat, vec)


M = torch.randn(2)
mat = torch.randn(2, 3)
vec = torch.randn(3)
r = torch.addmv(M, mat, vec)

mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 4)
r = torch.mm(mat1, mat2)

M = torch.randn(3, 4)
mat1 = torch.randn(3, 2)
mat2 = torch.randn(2, 4)
r = torch.addmm(M, mat1, mat2)

v1 = torch.arange(1, 4)    # Size 3
v2 = torch.arange(1, 3)    # Size 2
r = torch.ger(v1, v2)

vec1 = torch.arange(1, 4)  # Size 3
vec2 = torch.arange(1, 3)  # Size 2
M = torch.zeros(3, 2)
r = torch.addr(M, vec1, vec2)

batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
r = torch.bmm(batch1, batch2)

M = torch.randn(3, 2)
batch1 = torch.randn(5, 3, 4)
batch2 = torch.randn(5, 4, 2)
r = torch.addbmm(M, batch1, batch2)

## Backward

## Zero grad

## More cool stuff

In [ ]:
r = torch.diag(v1)

In [ ]:
torch.histc(torch.FloatTensor([1, 2, 1]), bins=4, min=0, max=3)


## Try it yourself: